name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: clippy, rustfmt

      - name: Install just
        uses: taiki-e/install-action@just

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run Lint
        run: just lint

  test-and-build:
    name: Test & Build Wasm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
          components: clippy, rustfmt

      - name: Install build tools
        uses: taiki-e/install-action@v2
        with:
          tool: just,wasm-bindgen-cli

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run Unit & Integration Tests
        run: just test

      - name: Build WebAssembly Release
        run: just build
